# Generated by Django 5.2.7 on 2025-10-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('anio_publicacion', models.IntegerField()),
                ('genero', models.CharField(choices=[('FICCION', 'FICCION'), ('MISTERIO', 'MISTERIO'), ('FANTASIA', 'FANTASIA'), ('CIENCIA_FICCION', 'CIENCIA_FICCION'), ('ROMANCE', 'ROMANCE'), ('TERROR', 'TERROR'), ('AVENTURA', 'AVENTURA'), ('HISTORICO', 'HISTORICO'), ('BIOGRAFIA', 'BIOGRAFIA'), ('AUTOAYUDA', 'AUTOAYUDA'), ('COMEDIA', 'COMEDIA'), ('DRAMA', 'DRAMA'), ('CIENCIAS', 'CIENCIAS')], default='CIENCIAS', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO'), ('S', 'SUSPENDIDO')], default='A', max_length=1)),
                ('rol', models.CharField(choices=[('AD', 'ADMINISTRADOR'), ('US', 'USUARIO')], default='US', max_length=2)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('materiallectura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.materiallectura')),
                ('isbn', models.CharField(max_length=13)),
                ('editorial', models.CharField(max_length=13)),
            ],
            bases=('api.materiallectura',),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('materiallectura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.materiallectura')),
                ('volumen', models.IntegerField()),
                ('editorial', models.CharField(max_length=13)),
            ],
            bases=('api.materiallectura',),
        ),
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('materiallectura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.materiallectura')),
                ('volumen', models.IntegerField()),
                ('editorial', models.CharField(max_length=255)),
            ],
            bases=('api.materiallectura',),
        ),
        migrations.CreateModel(
            name='RegistroLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pagina_actual', models.IntegerField()),
                ('estado', models.CharField(choices=[('LEYENDO', 'LEYENDO'), ('PENDIENTE', 'PENDIENTE'), ('TERMINADO', 'TERMINADO'), ('ABANDONADO', 'ABANDONADO')], default='PENDIENTE', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
    ]
